### ISSUE TITLE
see comment on the C170b about Jan @IPACS

### ISSUE THREAD

**Issue by Jetjockey10** [krzysk1/an2#1]
No need to repeat the same thing here.

Ray

**Comment by krzysk1** [comment]
we have to repeat it
Issues are reviewed separatelly

**Comment by Willie-Pretorius** [comment]
Hey 
I'm looking for the files for the Cessna C170b bush plane version I cant seem to find it under krzysk1's repositories. Can you please send me a link?

https://www.aerofly.com/community/forum/index.php?thread/14016-some-developments/&pageNo=6

![ready for the backcountry](https://user-images.githubusercontent.com/66911409/84595968-3b65b680-ae5b-11ea-9bcd-94e8478ef145.JPG)

Much appreciated. 

Pixelflames1

**Comment by krzysk1** [comment]
Hi,
I have to refresh my GitHub account, but not now.  I will do this after my vacation trip.

K



Od: Pixelflames1
Wysłano: niedziela, 14 czerwca 2020 16:23
Do: krzysk1/an2
DW: Krzysztof Kaniewski; State change
Temat: Re: [krzysk1/an2] see comment on the C170b about Jan @IPACS (#1)

Hey
I'm looking for the files for the Cessna C170b bush plane version I cant seem to find it under krzysk1's repositories. Can you please send me a link?
https://www.aerofly.com/community/forum/index.php?thread/14016-some-developments/&pageNo=6

Much appreciated.
Pixelflames1

**Comment by Jetjockey10** [comment]
It is good to hear from you.  Enjoy that vacation,

Regards,
Ray

**Comment by Willie-Pretorius** [comment]
Thank you so much enjoy your vacation. Sent from Mail for Windows 10 From: Jetjockey10Sent: Tuesday, June 16, 2020 2:58 PMTo: krzysk1/an2Cc: Pixelflames1; CommentSubject: Re: [krzysk1/an2] see comment on the C170b about Jan @IPACS (#1) It is good to hear from you. Enjoy that vacation,Regards,RaySent from my iPad> On Jun 16, 2020, at 12:25 AM, Krzysztof Kaniewski <notifications@github.com> wrote:> > ﻿> Hi,> I have to refresh my GitHub account, but not now. I will do this after my vacation trip.> > K> > > > Od: Pixelflames1> Wysłano: niedziela, 14 czerwca 2020 16:23> Do: krzysk1/an2> DW: Krzysztof Kaniewski; State change> Temat: Re: [krzysk1/an2] see comment on the C170b about Jan @IPACS (#1)> > Hey> I'm looking for the files for the Cessna C170b bush plane version I cant seem to find it under krzysk1's repositories. Can you please send me a link?> https://www.aerofly.com/community/forum/index.php?thread/14016-some-developments/&pageNo=6> > Much appreciated.> Pixelflames1> —> You are receiving this because you modified the open/close state.> Reply to this email directly, view it on GitHub, or unsubscribe.> > —> You are receiving this because you authored the thread.> Reply to this email directly, view it on GitHub, or unsubscribe.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
